version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ecofinance_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecofinance_network

  # Redis for JWT tokens
  redis:
    image: redis:7-alpine
    container_name: ecofinance_redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - ecofinance_network

  # MongoDB for analytics
  mongodb:
    image: mongo:6
    container_name: ecofinance_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecofinance_network

  # Auth Service
  auth-service:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: ecofinance_auth
    environment:
      - NODE_ENV=production
      - AUTH_PORT=${AUTH_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    depends_on:
      - postgres
      - redis
    networks:
      - ecofinance_network

  # Backend Service
  backend-service:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: ecofinance_backend
    environment:
      - NODE_ENV=production
      - BACKEND_PORT=${BACKEND_PORT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - MONGODB_URL=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DATABASE}
      - AUTH_SERVICE_URL=http://auth-service:${AUTH_PORT}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      - postgres
      - mongodb
      - auth-service
    networks:
      - ecofinance_network

  # Frontend Service
  frontend-service:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: ecofinance_frontend
    environment:
      - REACT_APP_AUTH_SERVICE_URL=http://localhost:${AUTH_PORT}
      - REACT_APP_BACKEND_SERVICE_URL=http://localhost:${BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - auth-service
      - backend-service
    networks:
      - ecofinance_network

volumes:
  postgres_data:
  mongodb_data:

networks:
  ecofinance_network:
    driver: bridge