version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: ecofinance_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ecofinance}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - ecofinance_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ecofinance_frontend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - ecofinance_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ecofinance_backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-ecofinance}
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - ecofinance_network

volumes:
  postgres_data:

networks:
  ecofinance_network:
    driver: bridge